unstable_features = true
binop_separator = "Front"
brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 50
format_code_in_doc_comments = true
format_macro_matchers = true
imports_indent = "Visual"
indent_style = "Visual"
match_arm_leading_pipes = "Preserve"
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 50
trailing_comma = "Never"
use_field_init_shorthand = true