[package]
name = "s2379_minimum_recolors_to_get_k_consecutive_black_blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
